CREATE DATABASE Empresa;
GO
USE Empresa;

CREATE TABLE DEPARTMENT(
	Dnumber INT PRIMARY KEY,
	Dname VARCHAR(50) NOT NULL,
	Mgr_ssn CHAR(9),
	Mgr_start_date DATE,
	CONSTRAINT FK_Mgr FOREIGN KEY (Mgr_ssn) REFERENCES EMPLOYEE(Ssn)
);

CREATE TABLE EMPLOYEE (
	Ssn CHAR(9) PRIMARY KEY,
	Fname VARCHAR(20) NOT  NULL,
	Minit CHAR(1),
	Lname VARCHAR(20) NOT NULL,
	Bdate DATE,
	Address VARCHAR(100),
	Sex CHAR(1) CHECK (Sex IN ('M', 'F')),
	Salary DECIMAL(10,2),
	Super_ssn CHAR(9),
	Dno INT,
	FOREIGN KEY (Dno) REFERENCES DEPARTMENT(Dnumber)
);

CREATE TABLE PROJECT (
    Pnumber INT PRIMARY KEY,
    Pname VARCHAR(50),
    Plocation VARCHAR(50),
    Dnum INT,
    FOREIGN KEY (Dnum) REFERENCES DEPARTMENT(Dnumber)
);

CREATE TABLE WORKS_ON (
    Essn CHAR(9),
    Pno INT,
    Hours DECIMAL(5,2),
    PRIMARY KEY (Essn, Pno),
    FOREIGN KEY (Essn) REFERENCES EMPLOYEE(Ssn),
    FOREIGN KEY (Pno) REFERENCES PROJECT(Pnumber)
);

CREATE TABLE DEPENDENT (
    Essn CHAR(9),
    Dependent_name VARCHAR(50),
    Sex CHAR(1),
    Bdate DATE,
    Relationship VARCHAR(20),
    PRIMARY KEY (Essn, Dependent_name),
    FOREIGN KEY (Essn) REFERENCES EMPLOYEE(Ssn)
);

CREATE TABLE DEPT_LOCATIONS (
    Dnumber INT,
    Dlocation VARCHAR(50),
    PRIMARY KEY (Dnumber, Dlocation),
    FOREIGN KEY (Dnumber) REFERENCES DEPARTMENT(Dnumber)
);

