CREATE TABLE Professor(
	ProfessorID INT NOT NULL PRIMARY KEY,
	CC CHAR(8) NOT NULL,
	Nome VARCHAR(64) NOT NULL,
	Morada VARCHAR(256) NOT NULL,
	Email VARCHAR(128) NOT NULL,
	DataNascimento DATE NOT NULL,
	Telefone INT NOT NULL,

);

CREATE TABLE Atividades(
	ID_Atividades INT NOT NULL PRIMARY KEY,
	Designacao VARCHAR(64) NOT NULL,
	Custo DECIMAL NOT NULL,
);

CREATE TABLE Turma(
	IDTurma INT NOT NULL PRIMARY KEY,
	Designacao VARCHAR(64) NOT NULL,
	Capacidade INT NOT NULL,
	Classe INT NOT NULL,
	AnoLetivo VARCHAR(9),
	ProfessorID INT NOT NULL FOREIGN KEY REFERENCES Professor(ProfessorID),
	ID_Atividades INT NOT NULL FOREIGN KEY REFERENCES Atividades(ID_Atividades),
);

CREATE TABLE Aluno(
	CC CHAR(8) NOT NULL PRIMARY KEY,
	Nome VARCHAR(64) NOT NULL,
	Morada VARCHAR(256) NOT NULL,
	DataNascimento DATE NOT NULL,
	IDTurma INT NOT NULL FOREIGN KEY REFERENCES Turma(IDTurma),
	ID_Atividades INT NOT NULL FOREIGN KEY REFERENCES Atividades(ID_Atividades),

);

CREATE TABLE Encarregado(
	CC CHAR(8) NOT NULL PRIMARY KEY,
	Nome VARCHAR(64) NOT NULL,
	Morada VARCHAR(256) NOT NULL,
	Email VARCHAR(128) NOT NULL,
	DataNascimento DATE NOT NULL,
	Telefone INT NOT NULL,
	Relacao_Aluno VARCHAR(64) NOT NULL,
	AlunoCC CHAR(8) NOT NULL FOREIGN KEY REFERENCES Aluno(CC),
);

CREATE TABLE PessoaAutorizada(
	CC CHAR(8) NOT NULL PRIMARY KEY,
	Nome VARCHAR(64) NOT NULL,
	Morada VARCHAR(256) NOT NULL,
	Email VARCHAR(128) NOT NULL,
	DataNascimento DATE NOT NULL,
	Telefone INT NOT NULL,
	Relacao_Aluno VARCHAR(64) NOT NULL,
	AlunoCC CHAR(8) NOT NULL FOREIGN KEY REFERENCES Aluno(CC),
);



