CREATE TABLE PESSOA(
	CC CHAR(8) NOT NULL PRIMARY KEY,
	Nome VARCHAR(64) NOT NULL,
	Morada VARCHAR(256) NOT NULL,
	Email VARCHAR(128),
	Telefone VARCHAR(16),
	DataNascimento DATE NOT NULL,
);

CREATE TABLE Professor(
	ProfessorID INT NOT NULL PRIMARY KEY,
	CC CHAR(8) NOT NULL FOREIGN KEY REFERENCES PESSOA(CC),

	UNIQUE(CC)
);

CREATE TABLE Atividades(
	ID_Atividade INT NOT NULL PRIMARY KEY,
	Designacao VARCHAR(64) NOT NULL,
	Custo DECIMAL(8,2) NOT NULL,
);

CREATE TABLE Turma(
	IDTurma INT NOT NULL PRIMARY KEY,
	Designacao VARCHAR(64) NOT NULL,
	Capacidade INT NOT NULL,
	Classe INT NOT NULL,
	AnoLetivo VARCHAR(9),
	ProfessorID INT NOT NULL FOREIGN KEY REFERENCES Professor(ProfessorID),
);

CREATE TABLE Aluno(
	CC  CHAR(8) NOT NULL FOREIGN KEY REFERENCES PESSOA(CC),
	IDTurma INT NOT NULL FOREIGN KEY REFERENCES Turma(IDTurma),

	PRIMARY KEY(CC),
);

CREATE TABLE TURMA_ATIVIDADE(
	IDTurma INT NOT NULL REFERENCES Turma(IDTurma),
	ID_Atividades INT NOT NULL FOREIGN KEY REFERENCES Atividades(ID_Atividade),

	PRIMARY KEY(IDTurma, ID_Atividades),
);

CREATE TABLE Encarregado(
	CC  CHAR(8) NOT NULL FOREIGN KEY REFERENCES PESSOA(CC),
	Relacao_Aluno VARCHAR(64) NOT NULL,
	AlunoCC CHAR(8) NOT NULL FOREIGN KEY REFERENCES Aluno(CC),

	PRIMARY KEY(CC)
);

CREATE TABLE PessoaAutorizada(
	CC  CHAR(8) NOT NULL FOREIGN KEY REFERENCES PESSOA(CC),
	Relacao_Aluno VARCHAR(64) NOT NULL,
	AlunoCC CHAR(8) NOT NULL FOREIGN KEY REFERENCES Aluno(CC),

	PRIMARY KEY(CC)
);