CREATE TABLE AIRPORT(
	Airport_Code VARCHAR(128) NOT NULL PRIMARY KEY,
	City VARCHAR(64) NOT NULL,
	Namw VARCHAR(64) NOT NULL,

	UNIQUE(Airport_Code),
);

CREATE TABLE AIRPLANE_Type(
	Airplane_Type_Name VARCHAR(64) NOT NULL PRIMARY KEY,
	Max_seats INT NOT NULL,
	Company VARCHAR(64) NOT NULL,

	UNIQUE(Airplane_Type_Name),
);

CREATE TABLE CAN_LAND(
	Airport_Code VARCHAR(128) NOT NULL FOREIGN KEY REFERENCES AIRPORT(Airport_Code),
	Airplane_Type_Name VARCHAR(64) NOT NULL FOREIGN KEY REFERENCES AIRPLANE_TYPE(Airplane_Type_Name), 
);


CREATE TABLE AIRPLANE(
	Airplane_ID INT NOT NULL PRIMARY KEY,
	Total_no_of_seats INT NOT NULL,
	Airplane_Type_Name VARCHAR(64) NOT NULL REFERENCES Airplane_Type(Airplane_Type_Name),

	UNIQUE(Airplane_ID),
);

CREATE TABLE FLIGHT(
	Flight_Number INT NOT NULL PRIMARY KEY,
	Airline VARCHAR(64) NOT NULL,
	Weekdays VARCHAR(64) NOT NULL,

	UNIQUE(Flight_Number),
);

CREATE TABLE FARE(
	Code VARCHAR(64) NOT NULL PRIMARY KEY,
	Amount INT NOT NULL,
	Restrictons VARCHAR(1024) NOT NULL,
	Flight_Number INT NOT NULL FOREIGN KEY REFERENCES FLIGHT(Flight_Number),

	UNIQUE(Code),
);

CREATE TABLE FLIGHT_LEG(
	Leg_no INT NOT NULL PRIMARY KEY,
	Schedule_dep_time DATETIME NOT NULL,
	Schedule_arr_time DATETIME NOT NULL,
	Flight_Number INT NOT NULL FOREIGN KEY REFERENCES FLIGHT(Flight_Number),

	UNIQUE(Leg_no),
);

CREATE TABLE LEG_INSTANCE(
	Instance_Date DATE NOT NULL PRIMARY KEY,
	No_of_avail_seats INT NOT NULL,
	Dep_time DATETIME NOT NULL,
	Arr_time DATETIME NOT NULL,
	Airport_Code VARCHAR(128) NOT NULL FOREIGN KEY REFERENCES AIRPORT(Airport_Code),
	Leg_no INT NOT NULL FOREIGN KEY REFERENCES FLIGHT_LEG(Leg_no),
	Airplane_ID INT NOT NULL FOREIGN KEY REFERENCES AIRPLANE(Airplane_ID),
);

CREATE TABLE SEAT(
	Seat_no INT NOT NULL PRIMARY KEY,
	Customer_Name VARCHAR(50) NOT NULL,
	Cphone VARCHAR(50) NOT NULL,
	Instance_Date DATE NOT NULl FOREIGN KEY REFERENCES LEG_INSTANCE(Instance_Date),
);